#
# Copyright (c) 2021, 2022 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

name: Eclipse OpenMQ CI

on:
  pull_request:

jobs:
  build:
    name: Test on JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java_version: [ 11, 17 ]

    steps:
    - name: Checkout for build
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java_version }}
    - name: Test Maven Build
      run: ./mvnw --show-version --no-transfer-progress --activate-profiles staging --file mq install
    - name: Upload MQ Distribution
      if: ${{ matrix.java_version == 11 }}
      uses: actions/upload-artifact@v2
      with:
        name: mq-distribution
        path: mq/dist/bundles/mq.zip

  build-with-no-staging:
    name: Build with no staging repository, using only central-released artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout for build
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Build OpenMQ
      run: ./mvnw --show-version --no-transfer-progress --file mq --define skipTests install

